services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzashop
    ports:
      - 5432:5432
    container_name: pizzashop-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
